export const light = {
  title: "light",
  colors: {
    main: "#ebedef",
    sidebar: "#06283D",
    header: "#ffffff",
    text: "#333",
    textSidebar: "#EEE",
    borders: "#1111",
    content: "#FFFF",
    sidebarLogo: "#321fdb",
    btnTabs: "#321fdb",
    betnTabsBorder: "#999F",
    btnInfoTab: "#a460ed",
    purpleHeader: "#7367F0",
    grayHeader: "#82868B",
    greenHeader: "#28C76F",
    redHeader: "#EA5455",
    blueHeader: "#00CFE8",
    orangeHeader: "#FF9F43",
    darkGrayHeader: "#4B4B4B",
  },
};
